local map = vim.keymap.set
map("n", "<leader>h", "<cmd>nohlsearch<CR>")
map("n", "<leader>tt", "<cmd>Telescope colorscheme<cr>")

map("n", "<leader>ff", "<cmd> Telescope find_files <cr>")
map("n", "<A-1>", "<cmd> BufferGoto 1 <cr>")
map("n", "<A-2>", "<cmd> BufferGoto 2 <cr>")
map("n", "<A-3>", "<cmd> BufferGoto 3 <cr>")
map("n", "<A-4>", "<cmd> BufferGoto 4 <cr>")
map("n", "<A-5>", "<cmd> BufferGoto 5 <cr>")
map("n", "<A-6>", "<cmd> BufferGoto 6 <cr>")
map("n", "<A-7>", "<cmd> BufferGoto 7 <cr>")
map("n", "<A-8>", "<cmd> BufferGoto 8 <cr>")
map("n", "<A-9>", "<cmd> BufferGoto 9 <cr>")
map("n", "<A-0>", "<cmd> BufferLast <cr>")
map("n", "<C-w>", "<cmd> BufferClose! <cr>")
map("n", "<leader>t", "<cmd> terminal <cr>")
map("t", "<esc>", "<c-\\><c-n>")
map({ "i", "n" }, "<c-f>", "<cmd>lua vim.lsp.buf.format() <cr>")
